version: '3'

services:
  zup:
    image: paulosalonso/zup:3.1.0
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/zup?useSSL=false&suseTimezone=true&serverTimezone=UTC
      - SPRING_DATASOURCE_username=postgres
      - SPRING_DATASOURCE_password=postgres
      - SPRING_DATASOURCE_driver-class-name=org.postgresql.Driver
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - postgres

  notifier:
    image: paulosalonso/notifier:0.0.1
    ports:
      - 8090:8090
    environment:
      SERVER_PORT: 8090
      NOTIFIER_EMAIL_SENDER: Paulo Alonso <paulo_alonso_@hotmail.com>
      NOTIFIER_EMAIL_SERVICE_TYPE: fake
      KAFKA_BROKER: kafka:9092
      KAFKA_SCHEMA_REGISTRY: http://schema-registry:8081
    depends_on:
      - zookeeper
      - kafka
      - schema-registry

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - /home/paulo/Documentos/Docker-Compose/Postgres:/var/lib/postgresql/data
      
#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: "mail@mail.com"
#      PGADMIN_DEFAULT_PASSWORD: "postgres"
#    ports:
#      - "16543:80"
#    depends_on:
#      - postgres

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181