
name: Docker Hub CD

on:
  release:

jobs:
  build-and-publish:
    name: Build and publish image in Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Project checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build package with Maven
        run: mvn -B package

      - name: Moving artifact to staging folder
        run: mkdir staging && cp zup-application/target/zup-application.jar staging

      - name: Uploading artifact
        uses: actions/upload-artifact@v1
        with:
          name: package
          path: staging
      
      - name: Login on Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build Docker image
        run: cd docker && make build:latest
        
      - name: Publish Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/zup
