
name: Maven CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build as a Maven project
    runs-on: ubuntu-latest
    steps:
      - name: Project checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build package with Maven
        run: mvn -B package

      - name: Moving artifact to staging folder
        run: mkdir staging && cp zup-application/target/zup-application.jar staging

      - name: Uploading artfact
        uses: actions/upload-artifact@v1
        with:
          name: package
          path: staging
  
  docker-image-publish:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      
      - name: Docker Hub Login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - run: cd zup-application && ls
      - run: cd target && ls
        
      - name: Build image
#         run: cd docker && docker build -t ${{ secrets.DOCKER_USERNAME }}/zup:latest .
        run: cd docker && make build:local
        
      - name: Publish Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/zup
